### PR TITLE
Added centos8 support

### PR DESCRIPTION
**Pull request by steveyminecraft**
Hi there I have been enjoying using the repo however I have wanted to expand the usage of the ansible code to work with  Centos-8 as I wish to use my Rpi’s to provide both DNS and Auth however FreeIPA server doesn’t work on Debain/Ubuntu at present, to that end I wish to install FreeIPA server onto the Rpi’s and retain the docker pihole deployment and have coded the support to enable this and wish to share back to the repo.

I have also added two options that allows for the installation of docker-compose and a second option to control weather the user account has it’s password locked as I found it interferes with testing.

Tested on 
Raspbin Bulls Eye aarch64
Centos-8 aarch64
Ubuntu 22.04 AMD64
Centos-8 AMD64

### CODE REVIEW

**Comment by shaderecker** [comment]
Hi @steveyminecraft, thanks for contributing! Just for your info: I will have time to review this in a couple of weeks as I'm busy right now. Feel free to add more commits in the meantime.

**Comment by steveyminecraft** [comment]
So I think I have finished my updates for now, maybe some smaller items to add however the repo now has support for CentOS-8 and uses gravity-sync for managing the pihoile DB transfer between the hosts

**Comment by steveyminecraft** [comment]
Any chance you are going to look at the PR?

**Comment by shaderecker** [comment]
Hi @steveyminecraft,
To be honest, I'm not so happy with this PR. It is quite large and touches all sorts of topics.
- Syntax/format changes in the readme and in many other files
- display.yaml: What is this needed for?
- files/dns.xml: This should be located in the respective role where it is used
- In inventory & keepalived.j2: `keepalive_role`: unused parameter, it is commented out in the template
- What is docker-compose needed here for?
- There are more OS distributions included, not just CentOS
- Any reason to switch to unicast_peer in keepalived?
- Where is the handler called in roles/pihole/handlers/main.yaml?
- Switch to gravity sync. Is this a personal preference?

I can see many useful improvements, however I will not merge this one big bang PR as it is unmanageable.

**Pull request closed without merging**
